services:
    open-webui:
        image: 'ghcr.io/open-webui/open-webui:main'
        restart: always
        container_name: open-webui
        volumes:
            - './open-webui:/app/backend/data'
        environment:
            - 'OLLAMA_BASE_URL=https://example.com'
        ports:
            - '9999:8080'
