################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    useBindPortIP: true
    exposedByDefault: true

################################################################
# TLS
################################################################
tls:
  stores:
    default:
      defaultGeneratedCert:
        resolver: myresolver
        domain:
          main: xxx.com

  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

################################################################
# ACME
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: anson1tsang@gmail.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
      certificatesDuration: 72

################################################################
# API & Dashboard
################################################################
api:
  insecure: true
  dashboard: true
