services:
  dpanel:
    image: 'dpanel/dpanel:lite'
    volumes:
        - './data:/dpanel'
        - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
        - APP_NAME=dpanel
    ports:
        - '8080:8080'
    restart: always
    container_name: dpanel
