version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    restart: always
    user: "${UID}:${GID}"
    ports:
      - 8080:8080
    volumes:
      - ./DATA_DIR:/data
      - ./CONFIG_DIR:/config
    environment:
      - FB_BASEURL=/filebrowser
