services:
  # MongoDB
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    # volumes:
    #   - ./DATA/mongodb:/data/db
  
  # Mongos Shell:
  # 寫入基礎數據
  # mongosh:
  #   build: 
  #     context: ./DATA/setup
  #     dockerfile: dockerfile
  #   container_name: mongosh
  #   network_mode: host # host mod 唔洗 ports
  #   # ports:
  #   #   - 8082:5000
  #   depends_on:
  #     - mongo

  mongo-express:
    image: mongo-express
    container_name: admin-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      # 設置 MongoDB 資料庫的用戶名和密碼
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      # 設置 Mongo Express Web 認證的用戶名和密碼
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    depends_on:
      - mongo