services:
  libretv:
    image: bestzwei/libretv:latest
    container_name: libretv
    ports:
      - "8899:8080"
    environment:
      - PASSWORD=${PASSWORD:-admin}
      - ADMINPASSWORD=${PASSWORD:-admin}
    restart: always