services:
  runner:
    image: gitea/act_runner
    container_name: gitea-docker-runner
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "${URL}"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: gitea-runner
      GITEA_RUNNER_LABELS: gitea-runner
    volumes:
      - ./config.yaml:/config.yaml
      - ./runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock