################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    useBindPortIP: true
    exposedByDefault: true
    
################################################################
# API & Dashboard
################################################################
api:
  insecure: true
  dashboard: true
